MODNAME		?= myrootkit

include $(src)/../Makefile.khook

obj-m		:= $(MODNAME).o
#myrootkit-objs := ./src/myrootkit.o ./src/process.o
$(MODNAME)-y	+= src/$(MODNAME).o src/process.o $(KHOOK_GOALS)

ccflags-y	+= $(KHOOK_CCFLAGS)
ldflags-y	+= $(KHOOK_LDFLAGS)
